# Enconder signal GPIO pin
ENCODER1_SIGNAL_PIN = 26
ENCODER2_SIGNAL_PIN = 4

# H Bridge GPIO pins
# IN3,IN4 (left motor); IN1,IN2 (right motor);
HBRIDGE_IN1 = 18
HBRIDGE_IN2 = 23
HBRIDGE_IN3 = 24
HBRIDGE_IN4 = 25

# Distance sensor GPIO pins
DISTANCE_TRIGGER = 5
DISTANCE_ECHO = 6
